---
title: "UFC Shiny App - Group 63"
author: "Patrick Pena-Aguilar - 306756892, Mateo Shelton - 706757700, Sohrab Sadjadi - 206754624"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```


```{r}
library(shiny)
library(shinythemes)
library(tidyverse)
library(plotly)
library(DT)
library(ggplot2)
library(ggmosaic)
library(rsconnect)

ufc_data <- read.csv("FighterStats.csv")

ui <- fluidPage( theme = shinytheme("lumen"),
  titlePanel("UFC Data Visualizer"),
  sidebarLayout(
    sidebarPanel(
      
      selectInput("data_category", "Choose Data Category:", choices = c("Numerical Data" = "numerical", "Categorical Data" = "categorical")),
      uiOutput("visualization_type_ui"),
      
      selectInput('weight', 'Weight class', choices = c('All', unique(ufc_data$Weight_Class)), selected = 'All'),
      
      selectInput('xvar', 'X variable', choices = names(ufc_data), selected = names(ufc_data)[13]),
      
      selectInput('yvar', 'Y variable', choices = names(ufc_data), selected = names(ufc_data)[14]),
      
      selectInput('zvar', 'Z variable', choices = names(ufc_data), selected = names(ufc_data)[15]),
      
      checkboxInput('jitter', 'Jitter scatter points', value = TRUE),
      
      hr(),
      
      downloadButton('download_data', 'Download filtered data')
    ),
    
    mainPanel(
      tabsetPanel(
        tabPanel('Plot', plotlyOutput('main_plot', height = '600px')),
        tabPanel('Data Table', DTOutput('table')),
        tabPanel('Summary', verbatimTextOutput('summary'))
      ),
      plotOutput("visualization_plot")
    )
  )
)


server <- function(input, output, session) {

  data <- reactive({
    if (is.null(input$file)) {
      return(ufc_data)     
    } else{
      return(read.csv(input$file$path))
    }   
    
  })
  # Dynamic Dataset for Weight Class
  filtered_data = reactive({
    if (input$weight == "All") {
      ufc_data
    } else {
      ufc_data %>%
        filter(Weight_Class == input$weight)
    }
  })
  
  output$fighter_table = renderTable({
    filtered_data()
  })

  output$main_plot <- renderPlotly({

    ufc_data <- read.csv("FighterStats.csv")
    
    plot_data = filtered_data()

    if (input$visualization_type == "Scatterplot") {

      p <- ggplot(plot_data, aes_string(x = input$xvar, y = input$yvar, fill = input$zvar)) +
        geom_point(alpha = 0.7, shape = 1)
      
      if (input$jitter == T) {
        p <- p + geom_jitter(alpha = 0.6)
      }
      ggplotly(p)
    } 
    
    else if (input$visualization_type == "Histogram") {
      
      if(!is.numeric(plot_data[[input$xvar]])) {
        validate(
          need(F, "Warning: Histograms require numeric data. Please select a different variable.")
        )
      }
      p <- ggplot(plot_data, aes_string(input$xvar, fill = input$zvar)) +
        geom_histogram(fill = "steelblue", color = "black", bins = 30)
      ggplotly(p)
      }
    
      else if (input$visualization_type == "Density Plot") {
        
         if(!is.numeric(plot_data[[input$xvar]])) {
        validate(
          need(F, "Warning: Denisty Plots require numeric data. Please select a different variable.")
        )
      }
      p <- ggplot(plot_data, aes_string(input$xvar)) +
        geom_density(fill = "lightgreen", alpha = 0.6)
      ggplotly(p)
      hwo 
      }
    
     else if (input$visualization_type == "Bar Plot") {
       
         if(!is.numeric(plot_data[[input$xvar]])) {
            validate(
          need(F, "Warning: Bar Plots require numeric data. Please select a different variable.")
        )
      }
      p <- ggplot(plot_data, aes_string(input$xvar)) +
        geom_bar(fill = "darkred") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1))
      ggplotly(p)
     }
  })
  
  # Data Visualization Type Dropdown 
  output$visualization_type_ui <- renderUI({
    if(input$data_category == "numerical"){
      selectInput("visualization_type", "Select Visualization Type:",
                  choice = c("Scatterplot", "Histogram", "Density Plot"))
      
    } else if(input$data_category == "categorical"){
      selectInput("visualization_type", "Select Visualization Type:",
                  choice = c("Bar Plot"))
    }
  })

  # Summary
  output$summary <- renderPrint({
    summary(data())
  })

  # Data Table
  output$table <- renderDT({
    datatable(data())
  })
  
  # Download filtered data
  output$download_data <- downloadHandler(
    filename = function() {
      "ufc_filtered_data.csv"
    },
    content = function(file) {
      write.csv(data(), file, row.names = FALSE)
    }
  )
}
shinyApp(ui, server)
```

